services:
  - type: web
    name: api-petshop
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        sync: false
      - key: ADMIN_NOME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_SENHA
        sync: false
